// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9JDL1mJ-IJAD2qAB17x1p-84SWepR814',
    appId: '1:271366593977:web:9efb305fdc4bc598aaaa68',
    messagingSenderId: '271366593977',
    projectId: 'emechanicfyp-8f13f',
    authDomain: 'emechanicfyp-8f13f.firebaseapp.com',
    storageBucket: 'emechanicfyp-8f13f.appspot.com',
    measurementId: 'G-BFY3F3Q5JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZc0R8pV5HwDe7Gn56d4cYFasLW3asCKk',
    appId: '1:271366593977:android:771e0d6ed5c34fe2aaaa68',
    messagingSenderId: '271366593977',
    projectId: 'emechanicfyp-8f13f',
    storageBucket: 'emechanicfyp-8f13f.appspot.com',
  );
}
